/**
 * Created by Administrator on 2016/6/18.
 */

export const GET_MY_BALANCE_REQUEST="GET_MY_BALANCE_REQUEST";
export const GET_MY_BALANCE_SUCCESS="GET_MY_BALANCE_SUCCESS";
export const GET_MY_BALANCE_FAILURE="GET_MY_BALANCE_FAILURE";

export const GET_BALANCE_DETAILS_REQUEST="GET_BALANCE_DETAILS_REQUEST";
export const GET_BALANCE_DETAILS_SUCCESS="GET_BALANCE_DETAILS_SUCCESS";
export const GET_BALANCE_DETAILS_FAILURE="GET_BALANCE_DETAILS_FAILURE";

