/*获取车列表*/
export const GET_CAR_LIST_REQUEST="GET_CAR_LIST_REQUEST";
export const GET_CAR_LIST_SUCCESS="GET_CAR_LIST_SUCCESS";
export const GET_CAR_LIST_FAILURE="GET_CAR_LIST_FAILURE";
/*删除车 */
export const DEL_CAR_REQUEST="DEL_CAR_REQUEST";
export const DEL_CAR_SUCCESS="DEL_CAR_SUCCESS";
export const DEL_CAR_FAILURE="DEL_CAR_FAILURE";