/* 获取优惠券列表 */
export const GET_COUPON_LIST_REQUEST="GET_COUPON_LIST_REQUEST";
export const GET_COUPON_LIST_SUCCESS="GET_COUPON_LIST_SUCCESS";
export const GET_COUPON_LIST_FAILURE="GET_COUPON_LIST_FAILURE";
