/**
 * Created by Administrator on 2016/9/6.
 */


export const GET_LAST_DAYS_REQUEST = "GET_LAST_DAYS_REQUEST";
export const GET_LAST_DAYS_SUCEESS = "GET_LAST_DAYS_SUCCESS";
export const GET_LAST_DAYS_FAILURE = "GET_LAST_DAYS_FAILURE";

export const GET_BANNER_REQUEST="GET_BANNER_REQUEST";
export const GET_BANNER_SUCCESS="GET_BANNER_SUCCESS";
export const GET_BANNER_FAILURE="GET_BANNER_FAILURE";

/**
* 获取版本信息
* @type {string}
*/
export const GET_VERSIONINFO_REQUEST = "GET_VISIONINFO_REQUEST";
export const GET_VERSIONINFO_SUCCESS = "GET_VISIONINFO_SUCCESS";
export const GET_VERSIONINFO_FAILURE = "GET_VISIONINFO_FAILURE";

/**
 * 添加版本日志
 * @type {string}
 */
export const EDIT_VERSION_LOG_REQUEST = "EDIT_VERSION_LOG_REQUEST";
export const EDIT_VERSION_LOG_SUCCESS = "EDIT_VERSION_LOG_SUCCESS";
export const EDIT_VERSION_LOG_FAILURE = "EDIT_VERSION_LOG_FAILURE";

/**
 * 获取配置提示信息
 * @type {string}
 */
export const GET_PROMPTINFO_REQUEST="GET_PROMPTINFO_REQUEST";
export const GET_PROMPTINFO_SUCCESS="GET_PROMPTINFO_SUCCESS";
export const GET_PROMPTINFO_FAILURE="GET_PROMPTINFO_FAILURE";

/**
 * 添加配置提示信息日志
 * @type {string}
 */
export const EDIT_PROMPTLOG_REQUEST="EDIT_PROMPTLOG_REQUEST";
export const EDIT_PROMPTLOG_SUCCESS="EDIT_PROMPTLOG_SUCCESS";
export const EDIT_PROMPTLOG_FAILURE="EDIT_PROMPTLOG_FAILURE";


