export const GET_VECODE_REQUEST = 'GET_VECODE_REQUEST';
export const GET_VECODE_SUCCESS = 'GET_VECODE_SUCCESS';
export const GET_VECODE_FAILURE = 'GET_VECODE_FAILURE';

export const CHECK_VECODE_REQUEST = 'CHECK_VECODE_REQUEST';
export const CHECK_VECODE_SUCCESS = 'CHECK_VECODE_SUCCESS';
export const CHECK_VECODE_FAILURE = 'CHECK_VECODE_FAILURE';

export const REGESTER_USER_REQUEST = 'REGESTER_USER_REQUEST';
export const REGESTER_USER_SUCCESS = 'REGESTER_USER_SUCCESS';
export const REGESTER_USER_FAILURE = 'REGESTER_USER_FAILURE';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
