/**
 * Created by Administrator on 2016/6/20.
 */
/**
 * 优惠券套餐信息
 * @type {string}
 */
export const GET_PACKAGE_LIST_REQUEST="GET_PACKAGE_LIST_REQUEST";
export const GET_PACKAGE_LIST_SUCCESS="GET_PACKAGE_LIST_SUCCESS";
export const GET_PACKAGE_LIST_FAILURE="GET_PACKAGE_LIST_FAILURE";

/**
 * 购物车信息
 * @type {string}
 */
export const GET_SHOPPING_CAR_REQUEST="GET_SHOPPING_CAR_REQUEST";
export const GET_SHOPPING_CAR_SUCCESS="GET_SHOPPING_CAR_SUCCESS";
export const GET_SHOPPING_CAR_FAILURE="GET_SHOPPING_CAR_FAILURE";

/**
 * 添加到购物车
 * @type {string}
 */
export const ADD_TO_SHOPPING_CAR_REQUEST="ADD_TO_SHOPPING_CAR_REQUEST";
export const ADD_TO_SHOPPING_CAR_SUCCESS="ADD_TO_SHOPPING_CAR_SUCCESS";
export const ADD_TO_SHOPPING_CAR_FAILURE="ADD_TO_SHOPPING_CAR_FAILURE";

/**
 * 删除购物车商品
 * @type {string}
 */
export const DELETE_BY_CAR_REQUEST="DELETE_BY_CAR_REQUEST";
export const DELETE_BY_CAR_SUCCESS="DELETE_BY_CAR_SUCCESS";
export const DELETE_BY_CAR_FAILURE="DELETE_BY_CAR_FAILURE";
