/*获取停车点列表 */
export const GET_PARK_LIST_REQUEST="GET_PARK_LIST_REQUEST";
export const GET_PARK_LIST_SUCCESS="GET_PARK_LIST_SUCCESS";
export const GET_PARK_LIST_FAILURE="GET_PARK_LIST_FAILURE";

/*删除停车点 */
export const DEL_PARK_REQUEST="DEL_PARK_REQUEST";
export const DEL_PARK_SUCCESS="DEL_PARK_SUCCESS";
export const DEL_PARK_FAILURE="DEL_PARK_FAILURE";