export const  GET_MAIN_PROPS_REQUEST="GET_MAIN_PROPS_REQUEST";
export const  GET_MAIN_PROPS_SUCCESS="GET_MAIN_PROPS_SUCCESS";
export const  GET_MAIN_PROPS_FAILURE="GET_MAIN_PROPS_FAILURE";

/**
 * 获取配置提示信息
 * @type {string}
 */
export const GET_PROMPTINFO_REQUEST="GET_PROMPTINFO_REQUEST";
export const GET_PROMPTINFO_SUCCESS="GET_PROMPTINFO_SUCCESS";
export const GET_PROMPTINFO_FAILURE="GET_PROMPTINFO_FAILURE";

/**
 * 添加配置提示信息日志
 * @type {string}
 */
export const EDIT_PROMPTLOG_REQUEST="EDIT_PROMPTLOG_REQUEST";
export const EDIT_PROMPTLOG_SUCCESS="EDIT_PROMPTLOG_SUCCESS";
export const EDIT_PROMPTLOG_FAILURE="EDIT_PROMPTLOG_FAILURE";

